version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./.docker/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - network
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
      - '9009:9009'
    expose:
      - 9000
      - 9009
    volumes:
      - ./app:/app
    networks:
      - network
  redis:
    build:
      context: ./.docker/redis
      dockerfile: Dockerfile
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - network
  redis-webui:
    build:
      context: ./.docker/redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    networks:
      - network
    ports:
      - "${REDIS_WEBUI_PORT}:80"
    depends_on:
      - redis
  mysql:
    container_name: mysql_db
    image: mysql:5.7
    command: mysqld --user=root
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      - network
networks:
  network:
    driver: bridge